###
POST http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Bundle
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation

{
    "resourceType": "Bundle",
    "type": "collection",
    "entry": [
      {
        "resource": {
          "resourceType": "Patient",
          "id": "1",
          "name": [{ "given": ["John"], "family": "Doe" }],
          "gender": "male",
          "birthDate": "1985-07-15"
        }
      },
      {
        "resource": {
          "resourceType": "Patient",
          "id": "2",
          "name": [{ "given": ["Jane"], "family": "Smith" }],
          "gender": "female",
          "birthDate": "1992-03-22"
        }
      },
      {
        "resource": {
          "resourceType": "Patient",
          "id": "3",
          "name": [{ "given": ["Robert"], "family": "Johnson" }],
          "gender": "male",
          "birthDate": "1978-11-10"
        }
      }
    ]
  }
     
  
###
GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Bundle/70257
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation


###
GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient?_id=4,5
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation

###
POST http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Bundle
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation

{
"resourceType": "Bundle",
"type": "collection",
"entry": [
 {
      "fullUrl": "http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient/4",
      "resource": {
        "resourceType": "Patient",
        "id": "4",
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: synthea-java .   Person seed: 5887668216735179003  Population seed: 1597764932523</div>"
        },
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString": "Terrilyn Reynolds"
          },
          {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueAddress": {
              "city": "Lynn",
              "state": "Massachusetts",
              "country": "US"
            }
          },
          {
            "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
            "valueDecimal": 2.252271652349974
          },
          {
            "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
            "valueDecimal": 62.747728347650025
          }
        ],
        "identifier": [
          {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "136ccd0c-6475-479a-9c0e-d6ce7517e20a"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "MR",
                  "display": "Medical Record Number"
                }
              ],
              "text": "Medical Record Number"
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "136ccd0c-6475-479a-9c0e-d6ce7517e20a"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "SS",
                  "display": "Social Security Number"
                }
              ],
              "text": "Social Security Number"
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "999-63-9154"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "DL",
                  "display": "Driver's License"
                }
              ],
              "text": "Driver's License"
            },
            "system": "urn:oid:2.16.840.1.113883.4.3.25",
            "value": "S99946482"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "PPN",
                  "display": "Passport Number"
                }
              ],
              "text": "Passport Number"
            },
            "system": "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
            "value": "X17037643X"
          }
        ],
        "name": [
          {
            "use": "official",
            "family": "Mann",
            "given": [
              "Suzann"
            ],
            "prefix": [
              "Mrs."
            ]
          },
          {
            "use": "maiden",
            "family": "Pollich",
            "given": [
              "Suzann"
            ],
            "prefix": [
              "Mrs."
            ]
          }
        ],
        "telecom": [
          {
            "system": "phone",
            "value": "555-680-4734",
            "use": "home"
          }
        ],
        "gender": "female",
        "birthDate": "1954-01-23",
        "address": [
          {
            "extension": [
              {
                "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                "extension": [
                  {
                    "url": "latitude",
                    "valueDecimal": 42.52924678277017
                  },
                  {
                    "url": "longitude",
                    "valueDecimal": -70.8591905796955
                  }
                ]
              }
            ],
            "line": [
              "295 Yundt Spur"
            ],
            "city": "Beverly",
            "state": "Massachusetts",
            "postalCode": "01915",
            "country": "US"
          }
        ],
        "maritalStatus": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
              "code": "M",
              "display": "M"
            }
          ],
          "text": "M"
        },
        "multipleBirthBoolean": false,
        "communication": [
          {
            "language": {
              "coding": [
                {
                  "system": "urn:ietf:bcp:47",
                  "code": "en-US",
                  "display": "English"
                }
              ],
              "text": "English"
            }
          }
        ],
        "meta": {
          "lastUpdated": "2025-03-12T13:18:55Z",
          "versionId": "1"
        }
      },
      "search": {
        "mode": "match"
      }
    },
    {
      "fullUrl": "http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient/5",
      "resource": {
        "resourceType": "Patient",
        "id": "5",
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: synthea-java .   Person seed: -3172650690484696193  Population seed: 1597764932523</div>"
        },
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString": "Elouise Rowe"
          },
          {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueAddress": {
              "city": "Weston",
              "state": "Massachusetts",
              "country": "US"
            }
          },
          {
            "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
            "valueDecimal": 1.018126792983423
          },
          {
            "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
            "valueDecimal": 24.981873207016577
          }
        ],
        "identifier": [
          {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "3e54e66d-7f18-4632-941c-9e609bcc3f48"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "MR",
                  "display": "Medical Record Number"
                }
              ],
              "text": "Medical Record Number"
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "3e54e66d-7f18-4632-941c-9e609bcc3f48"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "SS",
                  "display": "Social Security Number"
                }
              ],
              "text": "Social Security Number"
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "999-98-6011"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "DL",
                  "display": "Driver's License"
                }
              ],
              "text": "Driver's License"
            },
            "system": "urn:oid:2.16.840.1.113883.4.3.25",
            "value": "S99989281"
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code": "PPN",
                  "display": "Passport Number"
                }
              ],
              "text": "Passport Number"
            },
            "system": "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
            "value": "X11856351X"
          }
        ],
        "name": [
          {
            "use": "official",
            "family": "Paucek",
            "given": [
              "Stewart"
            ],
            "prefix": [
              "Mr."
            ]
          }
        ],
        "telecom": [
          {
            "system": "phone",
            "value": "555-492-5333",
            "use": "home"
          }
        ],
        "gender": "male",
        "birthDate": "1993-06-09",
        "address": [
          {
            "extension": [
              {
                "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                "extension": [
                  {
                    "url": "latitude",
                    "valueDecimal": 42.391840344018945
                  },
                  {
                    "url": "longitude",
                    "valueDecimal": -71.04031496719894
                  }
                ]
              }
            ],
            "line": [
              "876 Hoeger Trace Apt 56"
            ],
            "city": "Revere",
            "state": "Massachusetts",
            "postalCode": "02151",
            "country": "US"
          }
        ],
        "maritalStatus": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
              "code": "M",
              "display": "M"
            }
          ],
          "text": "M"
        },
        "multipleBirthBoolean": false,
        "communication": [
          {
            "language": {
              "coding": [
                {
                  "system": "urn:ietf:bcp:47",
                  "code": "en-US",
                  "display": "English"
                }
              ],
              "text": "English"
            }
          }
        ],
        "meta": {
          "lastUpdated": "2025-03-12T13:18:55Z",
          "versionId": "1"
        }
      },
      "search": {
        "mode": "match"
      }
    }
  ]

}


###
POST http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Bundle
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation


   